name: notes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  lottie: ^3.1.3
  easy_localization: ^3.0.8
  
  drift: ^2.24.2
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.26
  google_sign_in: ^7.2.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_messaging: ^16.1.1
  cloud_firestore: ^6.1.2
  intl: ^0.20.2
  googleapis: ^16.0.0
  googleapis_auth: ^2.0.0
  dio: ^5.9.1
  http_parser: ^4.1.2
  flutter_quill: ^11.5.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.24.2


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/1024.png
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/translations/
    - .env
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Courier
      fonts:
        - asset: assets/fonts/courier/CourierPrime-Regular.ttf
        # - asset: assets/fonts/courier/CourierPrime-Italic.ttf
        # - asset: assets/fonts/courier/CourierPrime-Bold.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
